---
title: "About"
format: html
editor: visual
---

This project was developed by Lucky 7 For [STA 199: Introduction to Data Science](https://sta199-s23-2.github.io/) at Duke University. The team is comprised of the following team members.

-   Ana Martinez is a first-year student majoring in Public Policy and receiving a certificate in Markets and Management. In her free time, Ana likes to bake, go to the gym, and play New York Times puzzles.

-   Whitney Clevenger is a second-year student majoring in Public Policy and receiving a certificate in Child Policy Research. In her free time, Whitney enjoys reading, weight-lifting, and going out to eat.

-   Sophia Correderas is a first-year student majoring in Psychology and Political Science. In her free time, Sophia enjoys rollerblading, singing at karaoke, and shopping.

-   Cameron Evans is a second-year student and Duke NCAA Men's Fencer majoring in History and Political Science with a minor in Asian and Middle Eastern Studies. In his free time, he enjoys fencing, reading, and spending time with friends.
