---
title: "lucky-7"
subtitle: "STA 199 Project"
format: html
editor: visual
---

**Project Abstract:**

Many consider the 21st century as the best time to be human as we are afforded luxuries and lifestyles that have never before been so accessible. But is this world safer? As technology and society develop, income inequality has skyrocketed, according to the Brookings Institution. Given this, our group "Lucky 7" looks to analyze how the world has become more violent over time, and if so, how GDP correlates with these observations. To analyze homicide rates over time, our group created visualizations from a United Nations data set illustrating homicide rates per region over time in 5-year increments; we also looked at these regions side-by-side to draw comparative results. To analyze these observations with GDP rates, our group created a regression analysis to determine the r-squared values of correlation, both based on region and globally. Through these observations, we determined that our first hypothesis, that the world has become less violent, is supported by the UN data. However, because there is mixed correlation between GDP and homicides, the results call into question our second hypothesis that GDP and violent crime are correlated.

\
